const FRASES_CARGA = [
  "Soplando el cartucho... 🌬️",
  "Procesando gráficos de 16 bits... 👾",
  "Conectando el chip Super FX... ⚡",
  "Cargando la Batería SRAM... 🔋",
  "Ajustando el Modo 7... 🏎️",
  "Desenredando el cable del mando... 🎮",
  "Insertando cartucho firmemente... 🕹️",
  "Sintonizando el canal 3 en la TV de tubo... 📺",
  "Limpiando los pines del cartucho... 🧪",
  "Activando el Blast Processing... 🚀",
  "Calibrando los botones L y R... 🎛️",
  "Preparando el cable Link... 🔗",
  "Sincronizando el audio chiptune... 🎵",
  "Aplicando el Código Konami... ⬆️⬆️⬇️⬇️",
  "Iniciando secuencias de 8 bits... 🧩",
  "Desbloqueando trucos con Game Genie... 🧞‍♂️",
  "Esperando a que se enfríe el transformador... 🔌",
  "Buscando pilas AA... 🔋",
  "Renderizando sprites retro... 🖼️",
  "Preparando al Player 1... 👤",
  "Revisando el manual de instrucciones... 📖",
  "Insertando moneda para continuar... 🪙",
  "Cargando mundos de píxeles... 🌍",
  "Soplando la ranura de la consola... 💨",
];
